# Generated by Django 4.1.5 on 2023-10-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('best_location', '0004_alter_information_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='owner',
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='userInformation', to=settings.AUTH_USER_MODEL),
        ),
    ]
