# Generated by Django 4.1.5 on 2023-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_location', '0005_remove_information_owner_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
