# Generated by Django 4.1.5 on 2023-11-13 10:51

from django.db import migrations, models

def convert_parking_place_to_int(apps, schema_editor):
    Information = apps.get_model('best_location', 'Information')
    for info in Information.objects.all():
        info.parking_place_int = 1 if info.parking_place else 2
        info.save()

class Migration(migrations.Migration):

    dependencies = [
        ('best_location', '0006_alter_information_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='parking_place_int',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(convert_parking_place_to_int),
        migrations.RemoveField(
            model_name='information',
            name='parking_place',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='parking_place_int',
            new_name='parking_place',
        ),
        migrations.AlterField(
            model_name='information',
            name='district_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='product_grade',
            field=models.IntegerField(),
        ),
    ]

