# Generated by Django 4.1.5 on 2023-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_location', '0006_alter_information_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='district_number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='parking_place',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='product_grade',
            field=models.FloatField(),
        ),
    ]
