# Generated by Django 5.1.2 on 2024-10-25 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_location', '0007_alter_information_district_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='parking_place',
            field=models.IntegerField(),
        ),
    ]
